# Runs the device tests on tvOS beta devices.

parameters:
- name: disableProviCleanup
  type: boolean
  default: false

- name: clearProviCache
  type: boolean
  default: false

resources:
  repositories:
  - repository: maccore
    type: github
    name: xamarin/maccore
    ref: refs/heads/device-tests-yaml # should this be on a branch and not on master???
    endpoint: xamarin

variables:
  - template: templates/variables.yml

stages:
- template: templates/device-tests-stage.yml
  parameters:
    testsLabels: '--label=run-tvos-tests,run-non-monotouch-tests,run-monotouch-tests,run-mscorlib-tests'
    statusContext: 'VSTS: device tests iOS'
    iOSDevicePool: 'VSEng-Xamarin-QA'
    iOSDeviceDemand: 'xitvos-beta'
    WindowsDevicePool: 'VSEng-Xamarin-Win-XMA'